### ISSUE TITLE
Error in Building

### ISSUE THREAD

**Issue by vbasky** [drdhaval2785/inriaxmlwrapper#3]
```Parsing of XMLs started at 2017-06-30 12:17:02.708110
Traceback (most recent call last):
  File "sanskritmark.py", line 26, in <module>
    upasargas = etree.parse('SL_upasargas.xml')
  File "src/lxml/lxml.etree.pyx", line 3442, in lxml.etree.parse (src/lxml/lxml.etree.c:81701)
  File "src/lxml/parser.pxi", line 1811, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118620)
  File "src/lxml/parser.pxi", line 1837, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:118967)
  File "src/lxml/parser.pxi", line 1741, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:117879)
  File "src/lxml/parser.pxi", line 1138, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:112425)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105881)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:107589)
  File "src/lxml/parser.pxi", line 633, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:106400)
IOError: Error reading file 'SL_upasargas.xml': failed to load external entity "SL_upasargas.xml"

**Comment by drdhaval2785** [comment]
https://github.com/drdhaval2785/inriaxmlwrapper/commit/1c6e34e010d7fc6b548056474dd4b61bce4fa29b closed this.
